server:
  port: 4865

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Security-service
          uri: http://localhost:5006
          predicates:
            - Path=/**
