#server:
#  port: 4865
#
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: Security-service
#          uri: http://localhost:5006
#          predicates:
#            - Path=/**

            
server:
  port: 4865
 
eureka:
  instance:
    hostname: localhost
 
spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
           allowedOrigins: "*"
           allowedMethods: "*"
           allowedHeaders: "*"
      routes:
      - id: user-service
        uri: lb://Security-service
        predicates:
          - Path=/**
       
            